spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    locations: classpath:/db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    out-of-order: true
    ignore-migration-patterns: '*:ignored'
    #default-schema: carrental
    schemas: carrental
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/CarRental"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/CarRental"

#    cache:
#      type: Caffeine
#      cache-names: roles, brand, models, car_types
#      caffeine:
#        spec: initialCapacity=10,maximumSize=20, expireAfterAccess=10s

  jpa:
    properties:
      javax.persistence.validation.mode: none
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.show_sql: true
      hibernate.connection.characterEncoding: utf8mb4
      hibernate.connection.CharSet: utf8mb4
      hibernate.connection.useUnicode: true
      hibernate.javax.cache.provider: net.sf.ehcache.hibernate.EhCacheProvider
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.cache.use_second_level_cache: true
      hibernate:
        cache:
          use_query_cache: true

server:
  port: 8080

---

jwt:
  secret: qwepuisdhfaksdjflsdfn12321___**
  expiration: 600000